/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sfproject3;

import javax.swing.JOptionPane;

/**
 *
 * @author thash
 */
public class AdminPracForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminPracForm
     */
    public AdminPracForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tblPrac = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtTitlePrac = new javax.swing.JTextField();
        txtModName = new javax.swing.JTextField();
        chkAvailableProj = new javax.swing.JCheckBox();
        txtStartDateProj = new javax.swing.JTextField();
        txtEndDatePrac = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDescriptionPrac = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnGoback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Practical_ID", "Practical_Title", "Description", "Module", "Start_Date", "End_Date", "Available"
            }
        ));
        tblPrac.setViewportView(jTable1);

        jPanel1.add(tblPrac, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 1000, 580));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInsert.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel2.add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, -1));

        btnDelete.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, -1));

        txtTitlePrac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitlePracActionPerformed(evt);
            }
        });
        jPanel2.add(txtTitlePrac, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 170, -1));
        jPanel2.add(txtModName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 150, -1));

        chkAvailableProj.setText("Available");
        jPanel2.add(chkAvailableProj, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        txtStartDateProj.setText("YYYY/MM/DD");
        jPanel2.add(txtStartDateProj, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 120, -1));

        txtEndDatePrac.setText("YYYY/MM/DD");
        jPanel2.add(txtEndDatePrac, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 120, -1));

        jLabel1.setText("Practical Title");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel2.setText("Practical Description");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel5.setText("Module Code");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel6.setText("Is the practical available?");
        jLabel6.setToolTipText("");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jLabel7.setText("When will the practical start?");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel8.setText("When will it end?");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));
        jPanel2.add(txtDescriptionPrac, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 170, 110));

        btnClear.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        jPanel2.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 310, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 370, 580));

        btnGoback.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnGoback.setText("<<Go Back");
        btnGoback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGobackActionPerformed(evt);
            }
        });
        jPanel1.add(btnGoback, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1461, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        // Code to load new data into  table
        //Accounting for Blanks
        if (txtTitlePrac.getText().equals("")||txtDescriptionPrac.getText().equals("")||txtModName.getText().equals("")||txtStartDateProj.getText().equals("")||txtEndDatePrac.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Some fields empty.");
        }
        //All fields filled
        else{
            String Title = txtTitlePrac.getText();
            String Des = txtDescriptionPrac.getText();
            //INCOMPLETE!!!!!!!!!!!!!!

        }

    }//GEN-LAST:event_btnInsertActionPerformed

    private void txtTitlePracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitlePracActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitlePracActionPerformed

    private void btnGobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGobackActionPerformed
        // TODO add your handling code here:
        //go back to adminHomePage(un)
        this.toBack();
        setVisible(false);
        new AdminProjForm().toFront();
        new AdminProjForm().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_btnGobackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPracForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPracForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPracForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPracForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPracForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGoback;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkAvailableProj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tblPrac;
    private javax.swing.JTextField txtDescriptionPrac;
    private javax.swing.JTextField txtEndDatePrac;
    private javax.swing.JTextField txtModName;
    private javax.swing.JTextField txtStartDateProj;
    private javax.swing.JTextField txtTitlePrac;
    // End of variables declaration//GEN-END:variables
}
