/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sfproject3;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javafx.scene.layout.Border;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.border.MatteBorder;

/**
 *
 * @author thash
 */
public class AdminHomePage extends javax.swing.JFrame {

    /**
     * Creates new form AdminHomePage
     */
    
    //Create borders
    MatteBorder default_border = BorderFactory.createMatteBorder(0, 0, 3, 0, new Color(153,153,153));
    MatteBorder red_border = BorderFactory.createMatteBorder(0, 0, 3, 0, Color.RED);
    
    //create array of buttons
    JButton[] buttons;
    public AdminHomePage() {
        initComponents();
    }

    AdminHomePage(String un) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this();
        this.setLocationRelativeTo(null);
        lblTitle.setText("Welcome " + un);
      
        //add buttons to the array
        buttons = new JButton[7];
        buttons[0] = btnDash;
        buttons[1] = btnPracticals;
        buttons[2] = btnProjects;
        buttons[3] = btnStudents;
        buttons[4] = btnStaff;
        buttons[5] = btnManage;
        buttons[6] = btnLogOut;
        
        //add default border to buttons
        for(JButton button : buttons){
        button.setBorder(default_border);
        }
        
        addAction();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnDash = new javax.swing.JButton();
        btnPracticals = new javax.swing.JButton();
        btnProjects = new javax.swing.JButton();
        btnStudents = new javax.swing.JButton();
        btnStaff = new javax.swing.JButton();
        btnManage = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        lblAdminWelcome2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 625));
        jPanel1.setPreferredSize(new java.awt.Dimension(916, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("University Allocation System");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 90));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnDash.setBackground(new java.awt.Color(255, 255, 255));
        btnDash.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnDash.setForeground(new java.awt.Color(153, 153, 153));
        btnDash.setText("Dashboard");
        btnDash.setBorder(null);
        btnDash.setContentAreaFilled(false);
        btnDash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnPracticals.setBackground(new java.awt.Color(255, 255, 255));
        btnPracticals.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnPracticals.setForeground(new java.awt.Color(153, 153, 153));
        btnPracticals.setText("Practicals");
        btnPracticals.setBorder(null);
        btnPracticals.setContentAreaFilled(false);
        btnPracticals.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnProjects.setBackground(new java.awt.Color(255, 255, 255));
        btnProjects.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnProjects.setForeground(new java.awt.Color(153, 153, 153));
        btnProjects.setText("Projects");
        btnProjects.setBorder(null);
        btnProjects.setContentAreaFilled(false);
        btnProjects.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnStudents.setBackground(new java.awt.Color(255, 255, 255));
        btnStudents.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnStudents.setForeground(new java.awt.Color(153, 153, 153));
        btnStudents.setText("Students");
        btnStudents.setBorder(null);
        btnStudents.setContentAreaFilled(false);
        btnStudents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnStaff.setBackground(new java.awt.Color(255, 255, 255));
        btnStaff.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnStaff.setForeground(new java.awt.Color(153, 153, 153));
        btnStaff.setText("Staff");
        btnStaff.setBorder(null);
        btnStaff.setContentAreaFilled(false);
        btnStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnManage.setBackground(new java.awt.Color(255, 255, 255));
        btnManage.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnManage.setForeground(new java.awt.Color(153, 153, 153));
        btnManage.setText("Manage");
        btnManage.setBorder(null);
        btnManage.setContentAreaFilled(false);
        btnManage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnLogOut.setBackground(new java.awt.Color(255, 255, 255));
        btnLogOut.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(153, 153, 153));
        btnLogOut.setText("Log out");
        btnLogOut.setBorder(null);
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDash, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPracticals, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManage, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnManage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnProjects, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPracticals, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStudents, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStaff, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 910, 70));

        lblAdminWelcome2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblAdminWelcome2.setText("Welcome");
        jPanel1.add(lblAdminWelcome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Create a function to add a mouseClick event to all buttons
    public void addAction(){
    for (JButton button: buttons){
    button.addMouseListener(new MouseListener() {

        @Override
        public void mouseClicked(MouseEvent e) {
            setButtonBorder(button);
        }

        @Override
        public void mousePressed(MouseEvent e) {
        }

        @Override
        public void mouseReleased(MouseEvent e) {
         
        }

        @Override
        public void mouseEntered(MouseEvent e) {
          
        }

        @Override
        public void mouseExited(MouseEvent e) {
           
        }
    });
    }
    }
   
    //Create function to set border to selected border item
    public void setButtonBorder(JButton button){
    
        //reset all buttons to default
        for (JButton btn: buttons){
        btn.setBorder(default_border);
        btn.setForeground(new Color(153,153,153));
        }
        
        //change to red border and black text when selected
        button.setBorder(red_border);
        button.setForeground(Color.black);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDash;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManage;
    private javax.swing.JButton btnPracticals;
    private javax.swing.JButton btnProjects;
    private javax.swing.JButton btnStaff;
    private javax.swing.JButton btnStudents;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAdminWelcome2;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
