/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sfproject3;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thash
 */
public class AdminPracForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminPracForm
     */
    public AdminPracForm() {
        initComponents();
        try{
            //open the connection
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb?useSSL=false", "root", "root@123");
            //here mydb is database name
            //root is username of mysql
            //root@123 is password
            // JOptionPane.showMessageDialog(null, "Database connection successful"); 
            String sqlPrac = "Select Practical_ID, Practical_Title, Description, Module, Start_Date, End_Date , Available from practicals";
            PreparedStatement pstPrac = con.prepareStatement(sqlPrac);
            ResultSet rsPrac = pstPrac.executeQuery(sqlPrac);
            
             while (rsPrac.next()){
            // data will be added until it gets to the end for practicals
                String Prac_ID = String.valueOf(rsPrac.getInt("Practical_ID"));
                String PracTitle = rsPrac.getString("Practical_Title");
                String PracDescription = rsPrac.getString("Description");
                String PracModuleCode = rsPrac.getString("Module");
                String StartDate = (rsPrac.getDate("Start_Date")).toString(); //YYYY-MM-DD
                String EndDate = (rsPrac.getDate("End_Date")).toString(); //YYYY-MM-DD
                //boolean to string
                boolean avaPrac = (rsPrac.getBoolean("Available"));
                String PracAva = "Unknown";

                if (avaPrac == true){
                PracAva = "No";
                }
                else if (avaPrac == false){
                PracAva = "Yes";
                }
               //String array to store data into jTable
                String tbPracData[] = {Prac_ID, PracTitle, PracDescription, PracModuleCode, StartDate, EndDate, PracAva};
                DefaultTableModel tblPracModel = (DefaultTableModel)jTable1.getModel();
                //add String array into jTabel
                tblPracModel.addRow(tbPracData);
            }
            }
            catch(Exception e){
            System.out.println(e.getMessage());
            //JOptionPane.showMessageDialog(null, "Error in connecting to database");
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tblPrac = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtTitlePrac = new javax.swing.JTextField();
        txtModName = new javax.swing.JTextField();
        chkAvailablePrac = new javax.swing.JCheckBox();
        txtStartDatePrac = new javax.swing.JTextField();
        txtEndDatePrac = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDescriptionPrac = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnGoback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Practical_ID", "Practical_Title", "Description", "Module", "Start_Date", "End_Date", "Available"
            }
        ));
        tblPrac.setViewportView(jTable1);

        jPanel1.add(tblPrac, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 1000, 580));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInsert.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel2.add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, -1, -1));

        btnDelete.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));

        txtTitlePrac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitlePracActionPerformed(evt);
            }
        });
        jPanel2.add(txtTitlePrac, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 170, -1));
        jPanel2.add(txtModName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 150, -1));

        chkAvailablePrac.setBackground(new java.awt.Color(255, 255, 255));
        chkAvailablePrac.setText("Available");
        chkAvailablePrac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAvailablePracActionPerformed(evt);
            }
        });
        jPanel2.add(chkAvailablePrac, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        txtStartDatePrac.setText("YYYY-MM-DD");
        jPanel2.add(txtStartDatePrac, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 120, -1));

        txtEndDatePrac.setText("YYYY-MM-DD");
        jPanel2.add(txtEndDatePrac, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 120, -1));

        jLabel1.setText("Practical Title");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel2.setText("Practical Description");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel5.setText("Module Code");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel6.setText("Is the practical available?");
        jLabel6.setToolTipText("");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jLabel7.setText("When will the practical start?");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel8.setText("When will it end?");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));
        jPanel2.add(txtDescriptionPrac, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 170, 110));

        btnClear.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 310, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sfproject3/checkMark.png"))); // NOI18N
        jLabel4.setText("Confirm Update");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 370, 580));

        btnGoback.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnGoback.setText("<<Go Back");
        btnGoback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGobackActionPerformed(evt);
            }
        });
        jPanel1.add(btnGoback, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1461, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        // Code to load new data into  table
        //Accounting for Blanks
        if (txtTitlePrac.getText().equals("")||txtDescriptionPrac.getText().equals("")||txtModName.getText().equals("")||txtStartDatePrac.getText().equals("")||txtEndDatePrac.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Some fields empty.");
        }
        //All fields filled
        else{
            String Title = txtTitlePrac.getText();
            String Des = txtDescriptionPrac.getText();
            String ModCode = txtModName.getText();
            String StartPracDate = txtStartDatePrac.getText();
            String EndPracDate = txtEndDatePrac.getText();
            Boolean AvailableChecking = false;
            if (chkAvailablePrac.isSelected()){
            AvailableChecking = true;
            }
            try{
            //open the connection
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb?useSSL=false", "root", "root@123");
            //here mydb is database name
            //root is username of mysql
            //root@123 is password
           // JOptionPane.showMessageDialog(null, "Database connection successful"); 
            
            String sql = "INSERT into practicals (Practical_Title, Description, Module, Start_Date, End_Date, Available) values (?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmt = con.prepareStatement(sql);
            
            pstmt.setString(1, Title);
            pstmt.setString(2, Des);
            pstmt.setString(3, ModCode);
            pstmt.setString(4, StartPracDate);
            pstmt.setString(5, EndPracDate);
            pstmt.setBoolean(6,AvailableChecking);
            
            int Count = pstmt.executeUpdate();
            if (Count != 0){
            JOptionPane.showMessageDialog(null, "Data successfully added");
            
            String sqlPrac = "Select Practical_ID, Practical_Title, Description, Module, Start_Date, End_Date , Available from practicals";
            PreparedStatement pstPrac = con.prepareStatement(sqlPrac);
            ResultSet rsPrac = pstPrac.executeQuery(sqlPrac);
            
             while (rsPrac.next()){
            // data will be added until it gets to the end for practicals
                String Prac_ID = String.valueOf(rsPrac.getInt("Practical_ID"));
                String PracTitle = rsPrac.getString("Practical_Title");
                String PracDescription = rsPrac.getString("Description");
                String PracModuleCode = rsPrac.getString("Module");
                String StartDate = (rsPrac.getDate("Start_Date")).toString(); //YYYY-MM-DD
                String EndDate = (rsPrac.getDate("End_Date")).toString(); //YYYY-MM-DD
                //boolean to string
                boolean avaPrac = (rsPrac.getBoolean("Available"));
                String PracAva = "Unknown";

                if (avaPrac == true){
                PracAva = "No";
                }
                else if (avaPrac == false){
                PracAva = "Yes";
                }
               //String array to store data into jTable
                String tbPracData[] = {Prac_ID, PracTitle, PracDescription, PracModuleCode, StartDate, EndDate, PracAva};
                DefaultTableModel tblPracModel = (DefaultTableModel)jTable1.getModel();
                //add String array into jTabel
                tblPracModel.addRow(tbPracData);}
            }
            else {JOptionPane.showMessageDialog(null, "Data not added");}
            }
            catch(Exception e){
            System.out.println(e.getMessage());
            //JOptionPane.showMessageDialog(null, "Error in connecting to database");
            }

        }

    }//GEN-LAST:event_btnInsertActionPerformed

    private void txtTitlePracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitlePracActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitlePracActionPerformed

    private void btnGobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGobackActionPerformed
        // TODO add your handling code here:
        //go back to adminHomePage(un)
        this.toBack();
        setVisible(false);
        new AdminProjForm().toFront();
        new AdminProjForm().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_btnGobackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int UserPrac_ID = (Integer.parseInt(JOptionPane.showInputDialog("Input the Practical_ID of the record you want to update:")));
        try{
            //open the connection
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb?useSSL=false", "root", "root@123");
            //here mydb is database name
            //root is username of mysql
            //root@123 is password
           // JOptionPane.showMessageDialog(null, "Database connection successful"); 
            String searchSQL = "Select Practical_Title, Description, Module, Start_Date, End_Date, Available from practicals WHERE Practical_ID = ? ";
            PreparedStatement searchStmt = con.prepareStatement(searchSQL);
            searchStmt.setInt(1, UserPrac_ID);
            ResultSet rsSearch = searchStmt.executeQuery();
            if (rsSearch.next()){
                txtTitlePrac.setText(rsSearch.getString("Project_Title"));
                txtDescriptionPrac.setText(rsSearch.getString("Description"));
                txtModName.setText(rsSearch.getString("Module"));
                txtStartDatePrac.setText(rsSearch.getString("Start_Date"));
                txtEndDatePrac.setText(rsSearch.getString("End_Date"));
                Boolean chckA = rsSearch.getBoolean("Available");
                if (chckA = true){
                    chkAvailablePrac.setSelected(true);        
                }
                else {chkAvailablePrac.setSelected(false);}
            }
            else {JOptionPane.showMessageDialog(null, "Record not found");}
        }
         catch(Exception e){
            System.out.println(e.getMessage());
            //JOptionPane.showMessageDialog(null, "Error in connecting to database");
            }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int UserPrac_ID = (Integer.parseInt(JOptionPane.showInputDialog("Input the Practical_ID of the record you want to update:")));
        try{
            //open the connection
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb?useSSL=false", "root", "root@123");
            //here mydb is database name
            //root is username of mysql
            //root@123 is password
           // JOptionPane.showMessageDialog(null, "Database connection successful"); 
            
            String sql = "Delete FROM practicals  WHERE Practical_ID = ?";
            PreparedStatement pstmt = con.prepareStatement(sql);
            
            pstmt.setInt(1, UserPrac_ID);
            
            int Count = pstmt.executeUpdate();
            if (Count != 0){
            JOptionPane.showMessageDialog(null, "Data successfully deleted");
            
            String sqlPrac = "Select Practical_ID, Practical_Title, Description, Module, Start_Date, End_Date , Available from practicals";
            PreparedStatement pstPrac = con.prepareStatement(sqlPrac);
            ResultSet rsPrac = pstPrac.executeQuery(sqlPrac);
            
             while (rsPrac.next()){
            // data will be added until it gets to the end for practicals
                String Prac_ID = String.valueOf(rsPrac.getInt("Practical_ID"));
                String PracTitle = rsPrac.getString("Practical_Title");
                String PracDescription = rsPrac.getString("Description");
                String PracModuleCode = rsPrac.getString("Module");
                String StartDate = (rsPrac.getDate("Start_Date")).toString(); //YYYY-MM-DD
                String EndDate = (rsPrac.getDate("End_Date")).toString(); //YYYY-MM-DD
                //boolean to string
                boolean avaPrac = (rsPrac.getBoolean("Available"));
                String PracAva = "Unknown";

                if (avaPrac == true){
                PracAva = "No";
                }
                else if (avaPrac == false){
                PracAva = "Yes";
                }
               //String array to store data into jTable
                String tbPracData[] = {Prac_ID, PracTitle, PracDescription, PracModuleCode, StartDate, EndDate, PracAva};
                DefaultTableModel tblPracModel = (DefaultTableModel)jTable1.getModel();
                //add String array into jTabel
                tblPracModel.addRow(tbPracData);}
            }
            else {JOptionPane.showMessageDialog(null, "Data not deleted");}
            }
         catch(Exception e){
            System.out.println(e.getMessage());
            //JOptionPane.showMessageDialog(null, "Error in connecting to database");
            }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtTitlePrac.setText("");
        txtDescriptionPrac.setText("");
        txtModName.setText("");
        txtStartDatePrac.setText("YYYY-MM-DD");
        txtEndDatePrac.setText("YYYY-MM-DD");
        chkAvailablePrac.setSelected(false);
    }//GEN-LAST:event_btnClearActionPerformed

    private void chkAvailablePracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAvailablePracActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAvailablePracActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        int UserPrac_ID = (Integer.parseInt(JOptionPane.showInputDialog("Confirm Practical_ID of the record you want to update:")));
        try{
            //open the connection
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb?useSSL=false", "root", "root@123");
            //here mydb is database name
            //root is username of mysql
            //root@123 is password
           // JOptionPane.showMessageDialog(null, "Database connection successful"); 
            
            String sql = "UPDATE practicals Practical_Title =?, Description=?, Module=?, Start_Date=?, End_Date=?, Available=? WHERE Practical_ID = ?";
            PreparedStatement pstmt = con.prepareStatement(sql);
            
            String Title = txtTitlePrac.getText();
            String Des = txtDescriptionPrac.getText();
            String ModCode = txtModName.getText();
            String StartPracDate = txtStartDatePrac.getText();
            String EndPracDate = txtEndDatePrac.getText();
            Boolean AvailableChecking = false;
            if (chkAvailablePrac.isSelected()){
            AvailableChecking = true;
            }
            
            pstmt.setString(1, Title);
            pstmt.setString(2, Des);
            pstmt.setString(3, ModCode);
            pstmt.setString(4, StartPracDate);
            pstmt.setString(5, EndPracDate);
            pstmt.setBoolean(6,AvailableChecking);
            pstmt.setInt(7, UserPrac_ID);
            
            int Count = pstmt.executeUpdate();
            if (Count != 0){
            JOptionPane.showMessageDialog(null, "Data successfully updated");
            
            String sqlPrac = "Select Practical_ID, Practical_Title, Description, Module, Start_Date, End_Date , Available from practicals";
            PreparedStatement pstPrac = con.prepareStatement(sqlPrac);
            ResultSet rsPrac = pstPrac.executeQuery(sqlPrac);
            
             while (rsPrac.next()){
            // data will be added until it gets to the end for practicals
                String Prac_ID = String.valueOf(rsPrac.getInt("Practical_ID"));
                String PracTitle = rsPrac.getString("Practical_Title");
                String PracDescription = rsPrac.getString("Description");
                String PracModuleCode = rsPrac.getString("Module");
                String StartDate = (rsPrac.getDate("Start_Date")).toString(); //YYYY-MM-DD
                String EndDate = (rsPrac.getDate("End_Date")).toString(); //YYYY-MM-DD
                //boolean to string
                boolean avaPrac = (rsPrac.getBoolean("Available"));
                String PracAva = "Unknown";

                if (avaPrac == true){
                PracAva = "Yes";
                }
                else if (avaPrac == false){
                PracAva = "No";
                }
               //String array to store data into jTable
                String tbPracData[] = {Prac_ID, PracTitle, PracDescription, PracModuleCode, StartDate, EndDate, PracAva};
                DefaultTableModel tblPracModel = (DefaultTableModel)jTable1.getModel();
                //add String array into jTabel
                tblPracModel.addRow(tbPracData);}
            }
            else {JOptionPane.showMessageDialog(null, "Data not updated");}
            con.close();
            }
            catch(Exception e){
            System.out.println(e.getMessage());
            //JOptionPane.showMessageDialog(null, "Error in connecting to database");
            }
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPracForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPracForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPracForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPracForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPracForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGoback;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkAvailablePrac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tblPrac;
    private javax.swing.JTextField txtDescriptionPrac;
    private javax.swing.JTextField txtEndDatePrac;
    private javax.swing.JTextField txtModName;
    private javax.swing.JTextField txtStartDatePrac;
    private javax.swing.JTextField txtTitlePrac;
    // End of variables declaration//GEN-END:variables
}
